# Generated by Django 3.2.7 on 2021-09-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_customershasaddresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersHasAddresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.address')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.customers')),
            ],
            options={
                'db_table': 'customers_has_addresses',
            },
        ),
    ]
