# Generated by Django 3.2.7 on 2021-09-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customershasaddresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhasitems',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderhasitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='OrderHasItems',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
