# Generated by Django 3.2.7 on 2021-09-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210918_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customershasaddresses',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.address'),
        ),
        migrations.AlterField(
            model_name='customershasaddresses',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customers'),
        ),
    ]
