# Generated by Django 3.2.7 on 2021-09-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210918_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomersHasFavoriteProducts',
        ),
    ]
