# Generated by Django 3.2.7 on 2021-09-27 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_customershasfavoriteproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersHasFavoriteProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customers')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
            options={
                'db_table': 'customers_has_favorite_products',
            },
        ),
    ]
