# Generated by Django 3.2.7 on 2021-09-27 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customershasfavoriteproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieshasproducts',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categories'),
        ),
        migrations.AlterField(
            model_name='categorieshasproducts',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
    ]
