# Generated by Django 3.2.7 on 2021-09-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_auto_20210915_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('productions_date', models.DateField(blank=True, null=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.products')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.customers')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderHasItems',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.items')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'order_has_items',
            },
        ),
    ]
