# Generated by Django 3.2.7 on 2021-09-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhasproduct',
            old_name='orderProducts',
            new_name='products',
        ),
    ]
